### ISSUE TITLE
Don't add a changeset if only `devDependencies` has changed.

### ISSUE THREAD

**Issue by cameronhunter** [mscharley/dependency-changesets-action#48]
Hi,

I've been experimenting with your package and it has been great so far, thanks for the effort you've put into it. I got a @dependabot pull request today that updating a `devDependency` and the workflow decided to create a changeset for it, but it would have no effect on the published package.

I see in the code that you're already reading the contents of the `package.json` files, but I wasn't sure how to add the feature myself.

Thanks again, Cameron

**Comment by mscharley** [comment]
Do you have an example PR that I can look at that demonstrates this?

The current behaviour will depend on the `use-semantic-commits` option:

* `true` (the default): It will select a relevant bump type based on the PR title. If the PR starts with `fix` then it will be a patch bump, if it starts with `feat` then it will be treated as a minor bump. There is currently no way to do a major bump via this integration. The correct way to do no bump with semantic commits would be to treat the PR as a `chore`.
* `false`: all package updates will be treated as patch updates.

**Comment by mscharley** [comment]
You should be able to configure dependabot to comply with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) using these options: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

**Comment by cameronhunter** [comment]
Thanks for looking into this! I've configured @dependabot to use conventional commits and it's working great now.

`dependabot.yml`:
```yml
version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      versioning-strategy: increase
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'fix'
          prefix-development: 'chore'
          include: 'scope'

```
